### PR TITLE
Update SOMns to version 0.7.0

### PR DESCRIPTION
**Pull request by smarr**
With the release of SOMns 0.7.0, I felt the need to get Moth up to date (see https://github.com/smarr/SOMns/releases/tag/v0.7.0).

This is a huge change. The release includes extension modules, support for snapshot writing, and major fixes for concurrency issues. The update to GraalVM 19 should eventually
bring Windows support.

For more reproducible research, SOMns comes now with a maintained artifact setup
out of the box.

Though, it will probably also bring some disruption since the setup changes, and for instance GraalBasic is not used any longer.

Before it can be considered for merging, some things need to be fixed:

 - [x] Fix tests https://travis-ci.org/smarr/Moth/builds/556040329#L2766
 - [ ] Make sure everyone can actually use it for their experiments 

@richard-roberts @kjx @IsaacOscar @Jamigrith any feedback/trying it out would be useful.
Only the commits from July 8th on are relevant for review.

### CODE REVIEW

**Comment by smarr** [comment]
I got a green run on the Moth repo with these changes: 
 https://travis-ci.org/smarr/Moth/builds/556213140

The SOMns CI setup is unfortunately not maintained, so, I'd suggest to leave fixing it to a later point in time.

**Comment by kjx** [comment]
I cloned the repo & etc. and built a Moth that ran "hello world:"

don't think I have Graal - but the CI log doesn't show Graal either...

**Comment by kjx** [comment]
So I now *think* I have Graal CE, and it also compiled and ran Hello World...

**Comment by smarr** [comment]
The current setup gets everything you need automatically. Removing hurdles where possible.
It will download a compatible JVM into `SOMns/libs/jvmci`.

This means, you need your normal Java to run `ant`. For everything else, it makes sure to grab compatible versions.

**Comment by kjx** [comment]
wow!  that means it's easier to install Graal via Moth than actual install Graal.

this is really great...

**Comment by smarr** [comment]
Ok, I think everyone got their chance to complain.
I'll merge.

**Pull request merged**
